language: objective-c
xcode_project: IceBuilder.xcodeproj
xcode_scheme: IceBuilder
notifications:
  slack:
    secure: O1PoU6qbgdiKQIV0/UAsjVwzJPlgag8fihFs2Pbm5nPgmsGQob3rDXT2UqpQydW6byNc7EWhUPoSLM1IoZdqgyVmqpnX//uMRPKm+UKthQ3U+LKqygJwp9WN4yYyd23RXvU8OciNcjwR3V7zRsigSXjoKPswyxoMYL0ezzRe/QY=
